%%%                                                         AMBIENTE DE TESTES
%%% 
%%% UTILIZA ESSE SCRIPT PARA TESTES, NÃO CRIE OUTROS
%%% PARA MELHOR FLEXBILIDADE CRIEI O SCRIPT test PARA FACILITAR
%%%
%%% FAVOR APAGAR O CODIGO APOS UTILIZAR O SCRIPT